### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by tealshift** [KingIsulgard/iOS-Polynomial-Regression#1]
Hi, I ran into this error when I used a degree of 50 on a fairly large dataset (a couple hundred x,y pairs).

It happened because in the function "decompose", the int maxPosition never got set after initialized to -1, which was then used as an array index in line 139.
Perhaps this is some overflow error?
Now, I'm not mathematically inclined, so that's all I can say for now. I'll mess around with it a bit more in the meantime.
Thanks so much for publishing this work!

**Comment by tealshift** [comment]
I forgot to mention that the method works when I use smaller degree counts.

I printed out dCurrentRatio this time and found that it was always either 0.00000 or nan, which I don't know how to interpret.

UPDATE: Indeed, there is 'double' overflow on one of the values in the 50x50 matrix. I can tell because other values in the same row went up near that astronomical number 1.797693e+308 which was DBL_MAX.

**Comment by KingIsulgard** [comment]
So how did you resolve the issue in your case?

**Comment by tealshift** [comment]
I don't believe I did find a solution, sorry.
