### ISSUE TITLE
Clarify Licence?

### ISSUE THREAD

**Issue by churowa** [KingIsulgard/iOS-Polynomial-Regression#2]
I'm wondering if you could clear up which licence this code is under.

The README says 'basically BSD; with attribution'
The Code says GPL
Github says GPL2.0

Thank you!

**Comment by KingIsulgard** [comment]
It's a GPL license as defined in the license file. 

What are you intended to use the code for?

**Comment by churowa** [comment]
I was looking at it for a client's project.

Basically drawing a curvy line through some points on a graph.

**Comment by KingIsulgard** [comment]
Yeah that's definitely okay. As long as you are not selling my code as is it's all good :D.
