### ISSUE TITLE
High macOS version requirements

### ISSUE THREAD

**Issue by noah-nuebling** [KingIsulgard/iOS-Polynomial-Regression#5]
Hi! This library seems very simple to use and exactly what I need but the high macOS requirements (macOS 12 or higher IIRC) prevented me from using it for my app.

If it’s possible it would be awesome to lower the requirements.

Thanks for considering.

**Comment by KingIsulgard** [comment]
Hi Noah,

Does this require any code changes? Because I no longer own a macbook for iOS development.
If it's just changing a config file via GIT I can do it though.

**Comment by noah-nuebling** [comment]
Hi Gilles, thanks for getting back!

I meant to post this issue under https://github.com/paescebu/PolynomialRegressionSwift. 
I ended up using your library and it works great.
