### ISSUE TITLE
Use in non-GPL project

### ISSUE THREAD

**Issue by noah-nuebling** [KingIsulgard/iOS-Polynomial-Regression#6]
Hi there Sam!

I'm making an app, and I've played around with some features using your library. Those features won't be published in a while but your library is already in the public source code of the "version-3" branch.

Now the problem is that my project is currently licensed under MIT, and I'm thinking about moving it to a license that I made up called the "MMF License" as I plan to monetize the app soon while keeping it open source, and I couldn't find any existing licenses for that purpose.

As far as I understand, this is not allowed under GPL. According to GPL, my whole project needs to be under GPL since your code is included and licensed under GPL.

So I'm asking you as the copyright holder for express permission to use your code in my project.
I'd really appreciated it, but of course I'll understand your decision whatever it may be.

Thanks!

---

Here is the "MMF License" I came up with: 

https://github.com/noah-nuebling/mac-mouse-fix/blob/version-3/LICENSE

**Comment by KingIsulgard** [comment]
Hello Noah,

Thank you for reaching out to me.
I'll see what license I should change it into.
The license is just there to avoid blatant reselling of the library, but I
have no issue with people using it for commercial applications.
So for now, feel free to already go ahead before I change the license. I
hereby give you permission.

By the way, thank you for your donation.

Kind regards,
Gilles Lesire

Op zo 11 sep. 2022 om 21:38 schreef Noah Nuebling ***@***.***

**Comment by noah-nuebling** [comment]
Great, thanks a lot Sam!
